# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ "$TERM" == "tmux-256color" ]]; then
  export TERM=screen-256color
fi

if [[ $TERM == "dumb" ]]; then
    export PS1="> "
fi

# Customize to your needs...
alias ec="/usr/local/bin/emacsclient -nw"
alias emacs="/usr/local/bin/emacs"
alias ecgui='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -c'
alias org="cd ~/Documents/org/"
alias note="ec ~/Documents/org/notes.org"
alias sdemacs="/usr/local/bin/emacsclient -e \"(kill-emacs)\""
alias jn=emacsclient -nw -e launch-journal

export ANSIBLE_NOCOWS=1

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        echo "Defer to PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

## Ruby
eval "$(rbenv init -)"

# Custom PATH
export PYTHON=/usr/local/Caskroom/miniconda/base/bin/python
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-14.0.2.jdk/Contents/Home
export MINICONDA=/usr/local/Caskroom/miniconda/base/bin:/usr/local/Caskroom/miniconda/base/condabin
export PATH=$HOME/.rbenv/shims:$MINICONDA:/usr/local/texlive/2023/bin/universal-darwin:$HOME/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/go/bin:$JAVA_HOME

# WORKON
export WORKON_HOME=$HOME/conda/envs