# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ "$TERM" == "tmux-256color" ]]; then
  export TERM=screen-256color
fi

# Customize to your needs...
alias ec="/usr/local/bin/emacsclient -nw"
alias emacs="/usr/local/bin/emacs"
alias ecgui='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -c'
alias org="cd ~/Documents/org/"
alias note="ec ~/Documents/org/notes.org"
alias sdemacs="/usr/local/bin/emacsclient -e \"(kill-emacs)\""
alias jn=emacsclient -nw -e launch-journal
alias R=R --no-save --no-restore

export ANSIBLE_NOCOWS=1

test -e $HOME/.iterm2_shell_integration.zsh && source $HOME/.iterm2_shell_integration.zsh
source $HOME/.iterm2_shell_integration.zsh

# Custom PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/texlive/2020/bin/x86_64-darwin/:$PATH
export PATH=$PATH:$HOME/go/bin

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/grivero/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/grivero/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/grivero/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/grivero/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

## Ruby
eval "$(rbenv init -)"

# fd - cd to selected directory
fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

# fh - search in your command history and execute selected command
fh() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

